define_plan:
  description: >
    User input example: 
    {user_info}
    Extract the role the user wants to become better at and their current knowledge level from the user input and learning goals.
    Define the structure and key points of a plan about how to most efficiently study in order to become a better role.
    The plan should be built around the needs of someone with current_knowledge_level knowledge of the role and learning goals.
    Ensure the plan's structure is layered and complete.
  expected_output: >
    A structured outline of the plan, including key points and sections to be covered.
    Expected output:
    {
      "role": "user_input",
      "current_knowledge_level": "user_input",
      "learning_goals": "user_input",
      "plan_outline": "A structured outline of the study plan with key points and sections."
    }
  agent: plan_definer

write_plan:
  description: >
    Fill in the {define_plan.output}.
    The plan should be built around the needs of someone with current knowledge level knowledge of the role and the learning goals.
    The plan must also include the following additional sections:
      Web resources
      Paper references
    Ensure the plan is detailed, layered, and easy to follow.
  expected_output: >
    A beautifully crafted and layered study plan to fill in with information.
    Expected output:
    {
      "detailed_plan": "A detailed and layered study plan."
    }
  agent: plan_writer
  context:
  - define_plan