define_plan:
  description: >
    Define the structure and key points of a plan about how to most efficiently study in order to become a better {job_role}.
    The plan should be built around the needs of someone with {current_knowledge_level} knowledge of the {job_role}, taking into account the user's previous experience: {past_experience}.
    Ensure the plan's structure is layered and complete.
  expected_output: >
    A structured outline of the plan, including key points and sections to be covered.
  agent: plan_definer

write_plan:
  description: >
    Write a plan about how to most efficiently study in order to become a better {job_role}.
    The plan should be built around the needs of someone with {current_knowledge_level} knowledge of the {job_role}, taking into account the user's previous experience: {past_experience}.
    Ensure the plan is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted and layered study plan to fill in with information.
  agent: plan_writer

review_plan:
  description: >
    Review the plan written by the plan_writer agent.
    Provide constructive feedback and suggest improvements if necessary.
  expected_output: >
    A list of actionable feedback points for the plan, with a focus on clarity, engagement, and completeness.
  agent: plan_reviewer