input_task:
  description: >
    Add context to the user's input by providing relevant background information and details.
  expected_output: >
    A comprehensive context that enhances the user's input and provides clarity and more information.
  agent: web_researcher

dalle_task:
  description: >
    Generate an image based on the description provided in the context.
  expected_output: >
    A high-quality image that accurately represents the input description.
  agent: dalle_agent