research_medical_query:
  description: >
    Research the medical query: "{medical_query}" using the available knowledge base.
    Use the qdrant_rag_search tool to find relevant medical information that can help answer the query.
    Focus on finding accurate, evidence-based information from reliable medical sources.
  expected_output: >
    A comprehensive collection of relevant medical information related to the query,
    including source citations and key medical facts that will help answer the question.
  agent: medical_researcher

analyze_medical_information:
  description: >
    Analyze the medical information retrieved for the query: "{medical_query}".
    Synthesize the information to provide a comprehensive, well-structured answer.
    Ensure the response is medically accurate, properly contextualized, and includes
    appropriate citations to the source materials.
  expected_output: >
    A well-structured, comprehensive answer to the medical query that includes:
    - Clear explanation of the medical topic
    - Key facts and important details
    - Proper source citations
    - Medical context and implications where relevant
  agent: medical_analyst
