fill_final_plan:
  description: >
    Fill in the final study plan with the resources and papers found by the previous agents.
    Ensure the plan's structure is layered and complete.
    Plan is a structured outline with key points and sections to be covered: {plan}
    Resources is a JSON with web resources grouped by section names from the input plan: {resources}
    Papers is a dictionary containing details of relevant scientific papers found for each topic: {papers}
  expected_output: >
    The final structured plan in markdown format.
  agent: final_plan_filler

write_ascii:
  description: >
    Create an ASCII flowchart that visually represents the most important steps of the study plan.
    The flowchart should be clear, engaging, and easy to understand, highlighting the key stages and transitions in the plan.
  expected_output: >
    Beautifully crafted ASCII flowcharts representing the most important steps of the study plan.
  agent: ascii_writer
  context: 
  - fill_final_plan

review_final_plan:
  description: >
    Review the plan written by the final_plan_filler agent.
    Insert the ascii flowcharts at the beginning of the plan.
  expected_output: >
    Final study plan in markdown format with ASCII flowcharts included.
  agent: final_plan_reviewer
  context: 
  - fill_final_plan
  - write_ascii